version: "3.8"

services:
  bot-example:
    build: .
    container_name: bot-example
    environment: &environment
      - BOT_CREDENTIALS=$BOT_CREDENTIALS  # cts_host@secret_key@bot_id
      - POSTGRES_DSN=postgres://postgres:postgres@bot-example-postgres/bot_example_db
      - REDIS_DSN=redis://bot-example-redis/0
      - DEBUG=true
      - SMARTLOG_DEBUG_HUIDS=$SMARTLOG_DEBUG_HUIDS
    ports:
      - "8000:8000"  # Отредактируйте порт хоста (первый), если он уже занят
    restart: always
    depends_on: &depends_on
      - postgres
      - redis
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ulimits: &ulimits
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  postgres:
    image: postgres:15.3-alpine
    container_name: bot-example-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bot_example_db
    restart: always
    volumes:
      - ./.storages/postgresdata:/var/lib/postgresql/data
    logging: *logging

  redis:
    image: redis:7.0-alpine
    container_name: bot-example-redis
    restart: always
    volumes:
      - ./.storages/redisdata:/data
    logging: *logging
